-- Sprint A (PLANO_FINAL): fase_atual em UPPER_SNAKE_CASE
ALTER TABLE processo DROP CONSTRAINT IF EXISTS processo_fase_atual_check;

UPDATE processo SET fase_atual = 'AGUARDANDO_AUDIENCIA'
WHERE fase_atual IN ('AUDIÊNCIA AGENDADA', 'AUDIENCIA AGENDADA', 'AGUARDANDO AUDIÊNCIA', 'AGUARDANDO AUDIENCIA');

UPDATE processo SET fase_atual = 'AGUARDANDO_PROCURACAO'
WHERE fase_atual IN ('AGUARDANDO PROCURAÇÃO', 'AGUARDANDO PROCURACAO');

UPDATE processo SET fase_atual = 'AGUARDANDO_SENTENCA'
WHERE fase_atual IN ('AGUARDANDO SENTENÇA', 'AGUARDANDO SENTENCA');

UPDATE processo SET fase_atual = 'AGUARDANDO_TRANSITO'
WHERE fase_atual IN ('AGUARDANDO TRÂNSITO', 'AGUARDANDO TRANSITO');

UPDATE processo SET fase_atual = 'AGUARDANDO_ALVARA'
WHERE fase_atual IN ('AGUARDANDO ALVARÁ', 'AGUARDANDO ALVARA');

UPDATE processo SET fase_atual = 'EM_RECURSO'
WHERE fase_atual = 'EM RECURSO';

UPDATE fase_historico SET fase_anterior = 'AGUARDANDO_AUDIENCIA'
WHERE fase_anterior IN ('AUDIÊNCIA AGENDADA', 'AGUARDANDO AUDIÊNCIA', 'AGUARDANDO AUDIENCIA');
UPDATE fase_historico SET fase_nova = 'AGUARDANDO_AUDIENCIA'
WHERE fase_nova IN ('AUDIÊNCIA AGENDADA', 'AGUARDANDO AUDIÊNCIA', 'AGUARDANDO AUDIENCIA');

UPDATE fase_historico SET fase_anterior = 'AGUARDANDO_PROCURACAO'
WHERE fase_anterior IN ('AGUARDANDO PROCURAÇÃO', 'AGUARDANDO PROCURACAO');
UPDATE fase_historico SET fase_nova = 'AGUARDANDO_PROCURACAO'
WHERE fase_nova IN ('AGUARDANDO PROCURAÇÃO', 'AGUARDANDO PROCURACAO');

UPDATE fase_historico SET fase_anterior = 'AGUARDANDO_SENTENCA'
WHERE fase_anterior IN ('AGUARDANDO SENTENÇA', 'AGUARDANDO SENTENCA');
UPDATE fase_historico SET fase_nova = 'AGUARDANDO_SENTENCA'
WHERE fase_nova IN ('AGUARDANDO SENTENÇA', 'AGUARDANDO SENTENCA');

UPDATE fase_historico SET fase_anterior = 'AGUARDANDO_TRANSITO'
WHERE fase_anterior IN ('AGUARDANDO TRÂNSITO', 'AGUARDANDO TRANSITO');
UPDATE fase_historico SET fase_nova = 'AGUARDANDO_TRANSITO'
WHERE fase_nova IN ('AGUARDANDO TRÂNSITO', 'AGUARDANDO TRANSITO');

UPDATE fase_historico SET fase_anterior = 'AGUARDANDO_ALVARA'
WHERE fase_anterior IN ('AGUARDANDO ALVARÁ', 'AGUARDANDO ALVARA');
UPDATE fase_historico SET fase_nova = 'AGUARDANDO_ALVARA'
WHERE fase_nova IN ('AGUARDANDO ALVARÁ', 'AGUARDANDO ALVARA');

UPDATE fase_historico SET fase_anterior = 'EM_RECURSO' WHERE fase_anterior = 'EM RECURSO';
UPDATE fase_historico SET fase_nova = 'EM_RECURSO' WHERE fase_nova = 'EM RECURSO';
